### ISSUE TITLE
Allow guarding (dynamic) module imports - a type for module specifiers

### ISSUE THREAD

**Issue by koto** [w3c/webappsec-trusted-types#117]
[Script modules](https://ponyfoo.com/articles/es6-modules-in-depth) [are here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#Standard_Import) i.e. there is a way of loading additional code from a URL to your application (previously you'd just append a new script, or `eval`). These come in a few flavors:

| Flavor | Syntax | Status |
|------|--------|----|
| standard import|`import {foo} from 'url'` | ECMA standard |
| [dynamic import](https://developers.google.com/web/updates/2017/11/dynamic-import) | `import(foo).then()` | [TC39 stage 3](https://github.com/tc39/proposal-dynamic-import/#import) | 
| [HTML modules](https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/master/HTMLModules/explainer.md) | `import {foo} from 'a.html'` | proposal |

These new code loading methods introduce a few interesting challenges:
1. There's no built in mechanism to add metadata to module names (~URLs). For example, there's no way to pass a nonce or a hash explicitly.
2. Apart from the dynamic import, there's no way to change what's being imported at runtime. Imports are parsed, loaded and linked before the execution of the module happens. 

For CSP side of things, this realistically means that only the `script-src` whitelist can somehow guard which modules are allowed to be run ([example problem](https://github.com/w3c/webappsec-csp/issues/375)). I'm not sure *if* and *how* Trusted Types can offer something here as well, given that they are a runtime feature. 

Mentioning a [related issue](https://github.com/tc39/proposal-dynamic-import/issues/26) as well, as it seems these concerns (code isolation, module limitations) are raised by other folks as well.

cc @arturjanc who raised the issue.

**Comment by koto** [comment]
There actually are some prior ideas about point 1 (adding metadata): https://discourse.wicg.io/t/specifying-nonce-or-integrity-when-importing-modules/1861

If these were implemented, at least the nonce or hash value could be generated and inserted server-side. 

That still doesn't solve point 2. (Trusted Types are at runtime), unless there's some code that can run in a non-module script _first_ that populates the whitelist, e.g.

```html
<script>
TrustedTypes.allowedScriptModules.push(modulePolicy.createTrustedScriptURL(foo))
TrustedTypes.allowedScriptModules.push(modulePolicy.createTrustedScriptURL('bar'))
</script>
<script type=module>
import {baz} from 'bazinga' // only works if allowedScriptModules contains 'bazinga'
</script>
```

**Comment by koto** [comment]
https://github.com/WICG/import-maps just surfaced and looks like an interesting mechanism to control / guard modules used by the application. There's two important issues though:

* no whiltelisting mode [issue](https://github.com/WICG/import-maps/issues/99)
* the map is [present in a document](https://github.com/WICG/import-maps#installation) (in a `<script type=importmap>` node), so it's yet another reflected XSS sink (and even a DOM XSS sink, as these can be modified [at runtime](https://github.com/WICG/import-maps#dynamic-import-map-example)). Maybe it's fine - it's a script after all.

**Comment by mikesamuel** [comment]
@koto, I'll play around to see whether there's a way to whitelist by having a single unscoped mapping like `/` to something like `about:invalid` and then using scopes to map specific other paths to override more specific patterns.

**Comment by mikesamuel** [comment]
# Update

Since https://github.com/WICG/trusted-types/issues/117#issue-400433270 dynamic import has been accepted as [stage 4](https://github.com/tc39/proposals/blob/master/finished-proposals.md) and will be part of EcmaScript 2020.

[Stage 0 Dynamic Import Host Adjustment](https://mikesamuel.github.io/dynamic-import-host-adjustment/) builds on that to allow vetting, and applying default policies to the argument to `import(...)`.

**Comment by mikesamuel** [comment]
## Open question: What is a conforming argument to `import(...)`?

Perhaps a *TrustedScriptURL* should be allowed.

Not all *moduleSpecifier*s are necessarily URLs though.
The [Standard Library Proposal](https://github.com/tc39/proposal-javascript-standard-library) covers some of the discussions about non-URL specifiers:

> **NPM Style**
>
> The Node Package Manager (NPM for short) has an established format for importing packages published to a central registry. The format allows packages to be grouped under organizations and this could be leveraged as a prefix for the JavaScript standard library:
>
>     import { ... } from "@std/SomeStandardModule";

The [import maps](https://github.com/WICG/import-maps) proposal distinguishes between "[URL-like](https://github.com/WICG/import-maps#general-url-like-specifier-remapping)" specifiers but leaves open that some specifiers may not be URL-like.

----

Defining a type *TrustedModuleSpecifier* would allow:

* Treating *TrustedModuleSpecifier* values as privileged inputs to `import(...)` regardless of whether the content string is URL-like or not.
* Optionally treating *TrustedScriptURL*'s as privileged URL-like inputs to `import(...)`.

----

If both a new *TrustedModuleSpecifier* and *TrustedScriptURL* are allowed, then when applying the default policy to a raw string, do we fallback from one of (*createModuleSpecifier*, *createScriptURL*) to the other?

**Comment by koto** [comment]
The neccessary primitivesin the language to be able to guard module imports is tracked in the [dynamic import host adjustment](https://github.com/tc39-transfer/dynamic-import-host-adjustment) TC39 proposal.

**Comment by koto** [comment]
Closing until after we have the necessary ECMAScript bits.
