### ISSUE TITLE
Event handler path not checking right name

### ISSUE THREAD

**Issue by mikesamuel** [w3c/webappsec-trusted-types#141]
https://github.com/WICG/trusted-types/blob/1f0e41ff742de43e70261814ac2b2d314b630e1e/src/enforcer.js#L657-L660

The third use of propertyName should probably be the attributeName from args since right now, that slice call should always return `'se'`.

**Comment by mikesamuel** [comment]
I'll fix this as part of some other cleanup.

**Comment by koto** [comment]
> The third use of propertyName should probably be the attributeName from args since right now, that slice call should always return `'se'`.

Why? There's an `||` in the `if`. This test should cover it: https://github.com/WICG/trusted-types/blob/9ede91b02ec6e0b7aa00ceb4a3ff427874fa43e8/tests/enforcer_test.js#L359 (well, there actually should be a test that a string is rejected).

**Comment by mikesamuel** [comment]
Can you assign this to me?  I saw something there which was confusing me, but don't have assign rights to this repo.

**Comment by koto** [comment]
Is this still occurring?

**Comment by koto** [comment]
This looks obsolete, please reopen if not.
