### ISSUE TITLE
Add a target suitable for nodejs.

### ISSUE THREAD

**Issue by koto** [w3c/webappsec-trusted-types#190]
That probably means publishing an npm package that 
  * implements the TT API only (equivalent of `api_only.js` entry point) (`TrustedTypes.createPolicy` etc.).
  * enforces restrictions (i.e. hook to prototype methods) on a given document-like and window-like objects - and a enforcement configuration (currently this is implemented as a CSP string).

These can be separate modules, but should all be packaged in one package, such that one can (I'm making up the API shape completely here):
```
import {TrustedTypes} from 'trusted-types/api.js';
import {enforceOn} from 'trusted-types/enforcement.js'; 
enforceOn(document, window, 'default': TrustedTypes.createPolicy('default', ...), violationCallback);
```

For the time being, this should probably be packaged as [CommonJS](https://flaviocopes.com/commonjs/) modules, as ES modules are still [experimental in Node 12](https://nodejs.org/api/esm.html), but we should explore how to migrate to ES modules eventually. It sounds like we might be able to package both variants together : https://nodejs.org/api/esm.html#esm_package_entry_points.

**Comment by koto** [comment]
@engelsdamien you probably would depend on the polyfill package?

**Comment by koto** [comment]
The current node package ([api_only as commonjs](https://github.com/WICG/trusted-types/blob/master/package.json#L5)) unfortunately breaks:

```
$ node
> require('.')
ReferenceError: HTMLIFrameElement is not defined
    at trustedTypesBuilderTestOnly (/usr/local/google/home/koto/dev/trusted-types/dist/cjs/trustedtypes.api_only.js:357:21)
    at Object.<anonymous> (/usr/local/google/home/koto/dev/trusted-types/dist/cjs/trustedtypes.api_only.js:684:5)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```

as we're now expecting a browser environment in [trustedtypes.js](https://github.com/WICG/trusted-types/blob/ea0358ad7b1e1ccde286e1cdbbacc1f24382dd4e/src/trustedtypes.js#L372), to test for browser behavior.

**Comment by koto** [comment]
https://www.npmjs.com/package/element-closest has something close to what we need. https://github.com/airbnb/browser-shims has a short list of polyfills we might take a look at for comparison.

**Comment by mikesamuel** [comment]
Is the idea that we provide an API that, given a TrustedTypesPolicyConfiguration and an HTMLDocument, returns a TrustedTypesPolicyFactory?

**Comment by koto** [comment]
Sorry for the late response. Yes :)
