### ISSUE TITLE
Overriding innerText and textContent does not work

### ISSUE THREAD

**Issue by domenic** [w3c/webappsec-trusted-types#227]
The spec in https://w3c.github.io/webappsec-trusted-types/dist/spec/#enforcement-in-script-text can be bypassed by using the value from the prototype.

```js
const textContentSetter = Object.getOwnPropertyDescriptor(Node.prototype, "textContent").set;

textContentSetter.call(someScriptEl, ...);
```

This code will not invoke the trusted types checks since it uses the Node.prototype version, not the HTMLScriptElement.prototype version.

This seems to argue for moving the checks closer to the actual primitives, perhaps using child text content changed steps of some sort.

**Comment by koto** [comment]
Good find!

Thankfully this doesn't work in the actual Chrome implementation, but I'll move the check up to `Node` and explore how could this be specced under the tt-at-primitives variant.

**Comment by koto** [comment]
This should be fixed now, as the specced setters (defined for a `script`) set the slot value, which the Node ones would not.
