### ISSUE TITLE
<iframe> and data: URLs?

### ISSUE THREAD

**Issue by domenic** [w3c/webappsec-trusted-types#228]
I noticed `iframe.srcdoc` is guarded, but not `iframe.src = 'data:text/html,...'`.

Is this intentional? If so, a note explaining what threat model makes these different would be a good idea to include in the spec.

**Comment by koto** [comment]
I might be missing something. Don't data: documents execute in a separate
origin? We mean to protect against code execution in our own origin, not js
execution in general (to do that we'd have to disallow navigating to
x-origin http/s URLs as well).

**Comment by koto** [comment]
To compare how iframe.src+data and iframe.srcdoc are different:

In `data:text/html,<iframe srcdoc="<script>alert(top.document.documentElement.innerHTML)</script>"></iframe>` the frame is same-origin to the doc document, whereas in `data:text/html,<iframe src="data:text/html,<script>alert(top.document.documentElement.innerHTML)</script>"></iframe>` it's not.

**Comment by domenic** [comment]
> We mean to protect against code execution in our own origin, not js execution in general (to do that we'd have to disallow navigating to x-origin http/s URLs as well).

That's the kind of thing I was hoping to get explained in a note about the threat model.

Regardless, what about `blob:` URLs? Those are same-origin, I believe.

**Comment by koto** [comment]
Blobs are tracked in #169.
