### ISSUE TITLE
getAttributeType is wrong about namespaces

### ISSUE THREAD

**Issue by annevk** [w3c/webappsec-trusted-types#240]
As currently defined it will never return what the examples say it will return. Attributes are not in a namespace by default.

**Comment by koto** [comment]
Don't steps 3 and 4 of [getAttributeType](https://w3c.github.io/webappsec-trusted-types/dist/spec/#dom-trustedtypepolicyfactory-getattributetype) solve this though? It should default to HTML namespace, as I'm getting the namespace from the element:

>    3. If |elementNs| is an empty string, set |elementNs| to [=HTML namespace=].
>    3. If |attrNs| is an empty string, set |attrNs| to |**elementNs**|'s value.

**Comment by annevk** [comment]
Attributes are not in a namespace by default.
