### ISSUE TITLE
"require-trusted-types-for Pre-Navigation check" versus "Get Trusted Type compliant string"

### ISSUE THREAD

**Issue by otherdaniel** [w3c/webappsec-trusted-types#246]
The following two bits of the spec appear to be largely doing the same thing, but are separately written in two different places:

https://w3c.github.io/webappsec-trusted-types/dist/spec/#require-trusted-types-for-pre-navigation-check (step 4++)
https://w3c.github.io/webappsec-trusted-types/dist/spec/#get-trusted-type-compliant-string-algorithm (performs - among others - the same steps)

Are these separate concepts that are expected to diverge, or are these conceptually the same thing, but just listed separately for editorial reasons?

(Context: This came up in a code review, with the underlying question being whether it's prudent to share the code that implements these or not.)

**Comment by koto** [comment]
Those two algorithms do different things - while the first one calls the default policy directly - and will be used to trigger CSP violation in CSP [pre-navigation check](https://www.w3.org/TR/CSP3/#ref-for-directive-pre-navigation-check), the latter only does so if the value is not a trusted type already - and triggers a separate CSP violation on its own. 

There is a possible optimization though - the logic for fetching & executing the default policy is already in https://w3c.github.io/webappsec-trusted-types/dist/spec/#process-value-with-a-default-policy-algorithm. I'll call that directly now in #250. Does that solve the issue?
