### ISSUE TITLE
require-trusted-types-for 'wasm'

### ISSUE THREAD

**Issue by lweichselbaum** [w3c/webappsec-trusted-types#256]
We could investigate if it makes sense to gate WASM compilation / instantiation by requiring a TrustedWasm or a TrustedWasmUrl.
This could replace or extend the proposed [Origin Bound Permission](https://github.com/WebAssembly/content-security-policy/blob/master/proposals/CSP.md#proposed-origin-bound-permission) in CSP for WASM.

**Comment by hackcasual** [comment]
How do trustedtypes work across worker/frame boundaries? It's a common pattern to compile a module on the main thread, then hand off the module for instantiation in worker threads. In that case origin information would be lost, but if a trusted type could be used to persist "chain of custody" I could see that being very useful

**Comment by koto** [comment]
Trusted Type instances are not Transferable, so you can't send them over to the other window or worker. You could hovewer create an instance locally where the risky function is being called (I assume this would be the module instantiation).

**Comment by binji** [comment]
@lweichselbaum: How would this effect the existing behavior of `WebAssembly.instantiateStreaming` and `WebAssembly.compileStreaming`?

@koto: I may be misunderstanding, but if we had a `TrustedWebAssemblyModule`, then you're saying we'd have to compile it separately on the main window and the worker?

**Comment by koto** [comment]
It depends which action we consider as security-critical. If it's compilation, the the compilation function would need a type. I suppose it's rather instantiation, so a type would have to be created locally in a window/workers that instantiates the already-compiled module. You'd still be passing compiled modules over postMessage, but the thread would "promote" them to being trusted (similarly, you can postMesage HTML snippets, and create a TrustedHTML locally before assigning to innerHMTL).

What information is available for a compiled module (the one that's transferred across scopes)?

**Comment by binji** [comment]
> You'd still be passing compiled modules over postMessage, but the thread would "promote" them to being trusted (similarly, you can postMesage HTML snippets, and create a TrustedHTML locally before assigning to innerHMTL).

OK, that sounds good then.

> What information is available for a compiled module (the one that's transferred across scopes)?

I'm not sure exactly what information you're looking for, but the compiled module is a [`WebAssembly.Module`](https://webassembly.github.io/spec/js-api/index.html#modules) object before and after transferring. There's not much you can do with a `Module` aside from query some information about export/import names, and custom sections (basically all static data). The currently spec'd behavior for transferring `WebAssembly.Module`s is in the [wasm web-api spec](https://webassembly.github.io/spec/web-api/index.html#serialization).

**Comment by hackcasual** [comment]
I've thought a bit about this over the past few months, and I'm just not sure TrustedTypes are a good fit for securing WebAssembly. For this, I'm intentionally ignoring possible functionality that a spec like: https://github.com/WebAssembly/esm-integration/tree/master/proposals/esm-integration would bring. The current way of working with WASM will remain, and it's those sets of operations I want to focus on. I feel that to whatever extent an ES module way of loading WASM changes the security impact, that should be addressed in the ESM spec, not anticipated by existing WASM work.

The primary focus of TrustedTypes from what I've read in the explainer and supporting docs is reducing the surface area of DOM XSS attacks. A WebAssembly module is itself not a DOM sink. Without being able to also execute JS, there is no way to create, execute, or interact with a WASM module. There is nothing equivalent to a javascript: url for WASM. Sure, it's possible to create WASM modules via XSS, but then [you're on the other side of an airtight hatchway](https://devblogs.microsoft.com/oldnewthing/20060508-22/?p=31283). If your web app is free of JavaScript XSS vulnerabilities, it will not have any WASM XSS vunlerabilities.

The primary mitigation in TrustedTypes seems to be sanitization. The source for WASM modules is binary, which is simply not something a web app is capable of sanitizing. At best a page could validate a cryptographic hash, but that would mean a substantial performance impact, and something better done with SRI (though with similar drawbacks).

An alternative would be to create a policy that can only be called in certain contexts, and trust the sequence of validation logic, something like

```javascript
function getTrustedWASM(wasmUrl) {
    if (isValidWASMSource) {
        return myPolicy.TrustedWASM(new fetch(wasmUrl));
    }
}
```

But I don't believe it's possible to have policies that can only be called from certain locations, and this isn't really a pattern other TrustedType policies should follow.

The one interesting area though would be as @lweichselbaum proposed a `TrustedWasmUrl`. WebAssembly's streaming methods though take Response objects, which means either having Response.url optionally be TrustedWasmUrl, or moving the trusted type up a level to TrustedWasmResponse. Doable, but if the only value add is URL checking, I'd question the value of doing it with TT vs CSP. You don't need to get your URL parsing right with CSP for example. It's easy to imagine something that lets through say '//evil.example/evil.wasm'

**Comment by koto** [comment]
Makes sense (and sorry for a very late response). We can assume that the WASM module doesn't have DOM XSSy capabilities in itself, they can only be given via JS bindings, and these are subject to Trusted Types (e.g. if your WASM module wants to operate on DOM, the DOM functions need to be given to it, with the necessary TT wrappings on the JS side).
