### ISSUE TITLE
Document.write and such as names are misleading

### ISSUE THREAD

**Issue by annevk** [w3c/webappsec-trusted-types#260]
The `Document` class does not have a static `write` property. I think we should make this `Document.prototype.write` or at least something that does not suggest a misleading thing (and which well might conflict in the future).

Via https://github.com/heycam/webidl/pull/841#issuecomment-586453624.

**Comment by koto** [comment]
Thanks, that's a good point. We're taking the data from the context object in steps 1.1 and 1.2 [here](https://w3c.github.io/webappsec-trusted-types/dist/spec/#!trustedtypes-extended-attribute), so it should be easy. There is still a potential collision as we're using the DOM local names for Elements for simplification.

**Comment by annevk** [comment]
I guess elements will always be lowercase? However, you probably want to distinguish SVG script from HTML script?

**Comment by koto** [comment]
There's probably no conflict possibility for static vs regular operations. In [WebIDL 2.5.3](https://heycam.github.io/webidl/#idl-operations):

> The identifier of a static operation also must not be the same as the identifier of a regular operation defined on the same interface

There's a similar restriction for attributes:

> The identifier of an attribute must not be the same as the identifier of another interface member defined on the same interface. The identifier of a static attribute must not be "prototype".

I looked into [our implementation](https://cs.chromium.org/chromium/src/third_party/blink/renderer/core/trustedtypes/trusted_types_util.cc?l=93&rcl=8cc471ecb167c819f29b10a5a3e9962ef5054d64), and it doesn't seem like we have the information to distinguish between prototype / static readily avaliable in the exception state. We actually (contrary to the spec) always use the constructor name, so:

```
data:text/html,<meta http-equiv="content-security-policy" content="require-trusted-types-for 'script'"><script>addEventListener('securitypolicyviolation', (e) => alert(e.sample));s=document.createElement('iframe');s.srcdoc = 'aaa'</script>
```

alerts `HTMLIframeElement.srcdoc`

It sounds like this might actually be a good outcome - if we always use the constructor name, that suggests to the authors that the sample contains the information about the sink in IDL (which is what the checks will hook on to), regardless on whether it's static or on the prototype.

**Comment by annevk** [comment]
I didn't realize IDL forbids conflicts, but I don't think it's a good idea to standardize on this rather misleading naming either.

cc @domenic

**Comment by domenic** [comment]
+1, as a web developer I find it supremely confusing when browser developers start talking about static methods and properties (like Document.write or HTMLIFrameElement.srcdoc) which do not exist.

At the very least, please use a different separator than "." A space would be a huge improvement.

**Comment by koto** [comment]
Agreed that we should not confuse - if changing the separator to a space, or anything else really makes it so devs are not confused that the value is the identifier of the IDL interface and not the ES object, I'm all for it. Space it is.

**Comment by koto** [comment]
Changes to the spec:
  * referred to IDL's this value identifier instead of object constructor name to signify we're closer to IDL. 
  * removed special casing for elements (e.g. `svg` => `SVGElement`)
  * used space instead of a dot, so "HTMLIframeElement srcdoc" will be the value passed to the default policy, and later to CSP violation.
  * eval violations continue use "eval".
  * used "HTMLScriptElement src" and  "HTMLScriptElement text" for violations when preparing a script. Added a todo for SVG scripts.
  * in CSP violation samples used `|` instead of a space to separate the sample prefix (sink name) from the payload (the string value). 

It's much better now, thanks all!

**Comment by ai-completed** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Security-Policy" content="default-src 'self';">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Trusted Types Implementation</title>
    <style>
        .error {
            color: red;
        }
    </style>
</head>
<body>

<h2>Trusted Types Test</h2>
<textarea id="userInput" rows="4" cols="50" placeholder="Enter your script..."></textarea>
<button onclick="executeScript()">Execute</button>
<p id="output" class="error"></p>

<script>
    // Define a comprehensive TrustedScript policy
    const disallowedSubstrings = ['<script>', 'eval(', 'window.', 'document.', 'fetch', 'XMLHttpRequest', 'import'];
    let opaqueScriptPolicy = trustedTypes.createPolicy('comprehensivePolicy', {
        createScript: opaqueScript => {
            for (let substring of disallowedSubstrings) {
                if (opaqueScript.includes(substring)) {
                    throw new Error(`Disallowed substring detected: ${substring}`);
                }
            }
            return opaqueScript;
        },
    });

    function sanitizeInput(input) {
        const sanitized = input.replace(/</g, '&lt;').replace(/>/g, '&gt;');
        return sanitized;
    }

    function validateAndSanitize(input) {
        if (typeof input !== 'string' || input.length > 1000) {
            throw new Error("Invalid input.");
        }
        return sanitizeInput(input);
    }

    function areAllTrustedScripts(args) {
        return args.every(arg => trustedTypes.isScript(arg));
    }

    function TrustedFunctionConstructor(...args) {
        if (!areAllTrustedScripts(args)) {
            throw new Error("All arguments must be TrustedScript instances");
        }
        return new Function(...args);
    }

    function executeScript() {
        const userInputElem = document.getElementById('userInput');
        const outputElem = document.getElementById('output');

        try {
            const userInput = userInputElem.value;
            const validatedInput = validateAndSanitize(userInput);
            const opaqueExpr = opaqueScriptPolicy.createScript(validatedInput);
            TrustedFunctionConstructor(opaqueExpr)();
            outputElem.textContent = "Script executed successfully!";
            outputElem.classList.remove('error');
        } catch (error) {
            outputElem.textContent = `Error: ${error.message}`;
            outputElem.classList.add('error');
        }
    }
</script>

</body>
</html>
