### ISSUE TITLE
Redefine behaviour for svg script href setter.

### ISSUE THREAD

**Issue by koto** [w3c/webappsec-trusted-types#275]
Redefine the behavior for SVG scripts as `svg:script.href` is not a string and it's defined via [SVGURIReference](https://www.w3.org/TR/SVG2/types.html#InterfaceSVGURIReference). 

// cc @otherdaniel

**Comment by otherdaniel** [comment]
Yeah, we overlooked that one.

I'm not quite sure if I understand all the implications of this being an animated string, but of-hand I'm seing two options, I think:
- make href.baseVal and href.animVal behave like TrustedScriptURL|DOMString.
- instead, have another "internal slot"-style mechanism.

Current preference is the first.

**Comment by koto** [comment]
We either need to fix it in `baseVal` setter (in that case we need to make sure we're only affecting the `baseVal` for script.href), or make the href for script not use that mixin, but another one.

**Comment by iVanlIsh** [comment]
I believe we moved every logic in the setter to binding process, so I'd prefer a union type TrustedScriptURL or DOMString. Not sure if we can easily implement it similar to other union type we currently have such as innerText in html_element.idl.
