### ISSUE TITLE
Operations must not be overloaded across interface, partial interface, etc.

### ISSUE THREAD

**Issue by foolip** [w3c/webappsec-trusted-types#283]
So says https://heycam.github.io/webidl/#idl-overloading:
> Operations must not be overloaded across interface, partial interface, interface mixin, and partial interface mixin definitions.

This is done a lot in this specification :)

**Comment by koto** [comment]
This spec defines how the integrations will look like, by monkey patching them inline. This is temporary, eventually the changes are to be merged to respective other specs. What's the recommended way to express that?

**Comment by foolip** [comment]
@koto there is no mechanism to redefine attributes to change their type or extended attributes, as is done here where the type is changed from `DOMString` to `HTMLString`:
https://w3c.github.io/webappsec-trusted-types/dist/spec/#enforcement-in-sinks
https://html.spec.whatwg.org/multipage/iframe-embed-object.html#htmliframeelement

Making this work would require some kind of order to know which definition "wins" or possibly that partial interfaces trump regular interfaces.

For operations (constructors, methods, etc.) it's also not possible, but in a slightly different way. Within a single interface or partial interface definition one can define overloads, and all defined variants of that method co-exist. The limitation cited from the spec is somewhat artificial, but probably a good idea since defining the actual steps of an operation across specs would get messy.

Practically speaking, it would be useful to separate the new things in this spec from that which is intended to replace definitions in other specs. The latter could be decorated with `class="idl exclude"` to avoid extracting those snippets into webref and WPT.

**Comment by koto** [comment]
> Practically speaking, it would be useful to separate the new things in this spec from that which is intended to replace definitions in other specs. 
Isn't this what the 'Integrations' section in the specs is about? 

If I understand, the nature of the changes poses the issues with the IDL extractor, but fundamentally it's what this spec is about - proposing new constructs and their integration - via IDL - with other specs, by redefining the interfaces. I'm happy to add 'idl exclude' if that helps, I just wanted to understand if I'm simply working around the IDL extractor limitation, or is there something else that this issue surfaces I should know about.

**Comment by foolip** [comment]
Sure, to a human reader it's clear what's going on in https://w3c.github.io/webappsec-trusted-types/dist/spec/#integrations, that those definitions replace other definitions.

The problem is for tooling. [Reffy](https://github.com/tidoust/reffy) scraped IDL from specs into [webref](https://github.com/w3c/webref), and then there are projects downstream from that, like [WPT](https://github.com/web-platform-tests/wpt/tree/master/interfaces) and [mdn-bcd-collector](https://github.com/foolip/mdn-bcd-collector) tries to use all of that IDL together. Almost all of the IDL works together, but the IDL in this spec can't be combined with the rest following the usual rules of Web IDL.

`class="idl exclude"` would be quickfix. If we wanted to be able to interpret the sum of all IDL in multiple ways, we'd need something like runtime flags in both this spec and the IDL that it replaces. Given how we use the IDL to generate only fairly surface-level tests, that doesn't seem worthwhile.

**Comment by koto** [comment]
Fixed (hopefully). Can you confirm?

**Comment by foolip** [comment]
https://github.com/w3c/webref/commit/987d2f6ab183a72599ee455e3b87d0f285cb1c56 is the scrape that but the right IDL wasn't excluded.

Arg, I've made this mistake before! https://github.com/tidoust/reffy/blob/master/src/browserlib/extract-webidl.js treats the exclude and extract classes the same, but Bikeshed does not when creating the IDL index, and that's what Reffy uses.

So, you'd need to use `class="idl extract"` instead of `class="idl exclude"`. However, that will also exclude these bits from the IDL index. Another way would be to just disable the IDL index, if you don't care about having it.

Sorry!

**Comment by koto** [comment]
Do you know how to disable the IDL index generation in Bikeshed? I wasn't able to find a config setting for that, it seems to be added [unconditionally](https://github.com/tabatkins/bikeshed/blob/ba857dcef0336d691037fbbd2cb9ba3b3f056c45/bikeshed/Spec.py#L215). It's a bit weird to have an index that ends up incomplete.

**Comment by foolip** [comment]
Per https://tabatkins.github.io/bikeshed/#bp-sections it should be:
```html
<pre class="metadata">
Boilerplate: idl-index no
</pre>
```
