### ISSUE TITLE
Trusted Types from other realms are allowed and don't check allowed policy names

### ISSUE THREAD

**Issue by TomiBelan** [w3c/webappsec-trusted-types#303]
I noticed a surprising consequence of the spec. There might not be anything wrong with it per se, but it's something to think about.

If you have two same-origin realms, then Trusted Types from one realm can be used in another realm. The "Get Trusted Type compliant string" algorithm does not check which realm created this Trusted Type, or whether the policy name would also be allowed by this sink realm. The `trusted-types` CSP directive is only checked at policy creation time.

Two examples (rename to .js extension and run with nodejs):
[example1.txt](https://github.com/w3c/webappsec-trusted-types/files/5638419/example1.txt) - if a parent frame has `trusted-types ttparent; require-trusted-types-for 'script'` and a child iframe has `trusted-types ttchild; require-trusted-types-for 'script'`, the spec allows `f.contentWindow.eval(ttparent.createScript('1+1'))` even though the TrustedScript was created with "ttparent", not "ttchild".
[example2.txt](https://github.com/w3c/webappsec-trusted-types/files/5638420/example2.txt) - if a parent fame has `trusted-types; require-trusted-types-for 'script'`, which is supposed to mean that policies may not be created, it can still create a policy using an iframe that doesn't have the same trusted-types directive.

I'm actually happy with the current behavior, it's very convenient for me, but I wasn't sure if it's intended to work this way. I don't want to rely on unintentional or undocumented behavior that might be subject to change. If the current behavior is actually intentional, it would be good to add a web platform test for it.

**Comment by koto** [comment]
It's intended, it's essentially a special case of https://w3c.github.io/webappsec-trusted-types/dist/spec/#cross-document-vectors.

**Comment by TomiBelan** [comment]
Thanks for confirming. Do you think it's worth it to add a web platform test for it, or is it adequately covered by existing tests? (I confess I didn't check what tests exist.)

**Comment by koto** [comment]
@otherdaniel do we have a test for this?
