### ISSUE TITLE
Mechanism to allow static HTML

### ISSUE THREAD

**Issue by shhnjk** [w3c/webappsec-trusted-types#340]
When we enforce Trusted Types, Trusted Types policy is required even for static HTML assignment (which never comes from user input).

Examples:

1.  https://source.chromium.org/chromium/chromium/src/+/master:ui/webui/resources/js/cr/ui/tree.js;l=320-321;drc=56de816e7df5874cc1775439ff5f0a6aabcdfd11
2. https://source.chromium.org/chromium/chromium/src/+/master:ui/webui/resources/js/cr/ui/bubble.js;l=84-88;drc=6e82ffa4ab779589119ba9cf5d8a5fe6720b2deb
3. https://source.chromium.org/chromium/chromium/src/+/master:out/Debug/gen/ui/webui/resources/preprocessed/cr_components/omnibox/cr_autocomplete_match_list.js;l=19-24;drc=279ef98c9e6917879e747d483abc2110a242ffd2

Script URL has a proposed solution for this called [Array.isTemplateObject](https://github.com/tc39/proposal-array-is-template-object).

Can we have a solution for static HTML as well? Maybe `trustedTypes.toHTML()` where it checks that a string passed is a static string (similar to `Array.isTemplateObject`)? 
Or should we wait for [HTML Modules](https://github.com/WICG/webcomponents/blob/gh-pages/proposals/html-modules-explainer.md)?

**Comment by koto** [comment]
`Array.isTemplateObject` is not limited to TrustedScriptURLs, it's a generic method that can be used for either type.
