### ISSUE TITLE
Jquery Js getting reported error with TrustedTypes implementation

### ISSUE THREAD

**Issue by vijaysn2702** [w3c/webappsec-trusted-types#362]
We implemented trusted types for sanitization purpose and we running in report only mode, Browser is reporting the "This document requires 'TrustedHTML' assignment" for Jquery.js. for other js files getting error as "This document requires 'TrustedScriptURL' assignment", please let us know the cause of this error.

**Comment by koto** [comment]
This repository is for tracking issues with the TT spec or the polyfill. 

From what you are describing, the application is passing a string to a sink that requires a `TrustedScriptURL` (e.g. a `src` attribute of a `script` element) - for jQuery that might be caused e.g. by a code like: `$(script).attr('src', 'https://example.com')`, but we can't really help debug specific applications.
