### ISSUE TITLE
Polyfill script link on w3c.github.io gives 404

### ISSUE THREAD

**Issue by siMs0n** [w3c/webappsec-trusted-types#373]
It seems like the polyfill script can no longer be found on https://w3c.github.io/webappsec-trusted-types/dist/es5/trustedtypes.build.js as specified in the README

The demo site using the same link is therefor also broken on Firefox for example https://w3c.github.io/webappsec-trusted-types/demo/

Can you make it available on the link again or somewhere else?

**Comment by koto** [comment]
Oops! Thanks for pointing it out. Fixed :)
